<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GuruSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('gurus')->insert([
            [
                'id' => 1,
                'nip' => 1322,
                'nama_guru' => 'Evan Septya Utama',
                'no_telp' => '081311212',
                'alamat_guru' => 'Jl. Selamat 1, No.27, Sangatta Utara, Kutai Timur, Kalimantan Timur',
                'tempat_lahir' => 'Sangatta',
                'ttl' => '1992-01-01',
                'foto_pengajar' => 'Siswa/foto.jpg',
                'jabatan' => 'Kepala Sekolah',
                'agama' => 'Protestan',
                'suku' => 'Toraja',
                'rt_rw' => '005/000',
                'desa_kelurahan' => 'Teluk Lingga',
                'kecamatan' => 'Sangatta Utara',
                'kode_pos' => 75622,
            ],
            [
                'id' => 2,
                'nip' => 13222,
                'nama_guru' => 'Petrus Kaba',
                'no_telp' => '22342232342',
                'alamat_guru' => 'Jl. Selamat 11, No.27, Sangatta Utara, Kutai Timur, Kalimantan Timur',
                'tempat_lahir' => 'Jakarta',
                'ttl' => '1992-01-01',
                'foto_pengajar' => 'Siswa/foto.jpg',
                'jabatan' => 'Kepala Sekolah',
                'agama' => 'Protestan',
                'suku' => 'Batak',
                'rt_rw' => '002/000',
                'desa_kelurahan' => 'Teluk Lingga',
                'kecamatan' => 'Sangatta Utara',
                'kode_pos' => 75622,
            ],
            [
                'id' => 3,
                'nip' => 13242,
                'nama_guru' => 'Bu Sarje',
                'no_telp' => '091231321',
                'alamat_guru' => 'Jl. Selamat 21, No.27, Sangatta Utara, Kutai Timur, Kalimantan Timur',
                'tempat_lahir' => 'Sangatta',
                'ttl' => '1992-01-01',
                'foto_pengajar' => 'Siswa/foto.jpg',
                'jabatan' => 'Kepala Sekolah',
                'agama' => 'Protestan',
                'suku' => 'Manado',
                'rt_rw' => '003/000',
                'desa_kelurahan' => 'Teluk Lingga',
                'kecamatan' => 'Sangatta Utara',
                'kode_pos' => 75622,
            ],
            [
                'id' => 4,
                'nip' => 132252,
                'nama_guru' => 'Madam Dewi',
                'no_telp' => '83424234',
                'alamat_guru' => 'Jl. Selamat 1, No.27, Sangatta Utara, Kutai Timur, Kalimantan Timur',
                'tempat_lahir' => 'Bontang',
                'ttl' => '1992-01-01',
                'foto_pengajar' => 'Siswa/foto.jpg',
                'jabatan' => 'Kepala Sekolah',
                'agama' => 'Protestan',
                'suku' => 'Toraja',
                'rt_rw' => '012/000',
                'desa_kelurahan' => 'Teluk Lingga',
                'kecamatan' => 'Sangatta Utara',
                'kode_pos' => 75622,
            ],
            [
                'id' => 5,
                'nip' => 132262,
                'nama_guru' => 'Bu Darmi',
                'no_telp' => '1312131',
                'alamat_guru' => 'Jl. Selamat 1, No.27, Sangatta Utara, Kutai Timur, Kalimantan Timur',
                'tempat_lahir' => 'Jakarta',
                'ttl' => '1992-01-01',
                'foto_pengajar' => 'Siswa/foto.jpg',
                'jabatan' => 'Kepala Sekolah',
                'agama' => 'Protestan',
                'suku' => 'Toraja',
                'rt_rw' => '017/000',
                'desa_kelurahan' => 'Teluk Lingga',
                'kecamatan' => 'Sangatta Utara',
                'kode_pos' => 75622,
            ],
            [
                'id' => 6,
                'nip' => 132263,
                'nama_guru' => 'Bu Fransiswa',
                'no_telp' => '34231231',
                'alamat_guru' => 'Jl. Selamat 111, No.27, Sangatta Utara, Kutai Timur, Kalimantan Timur',
                'tempat_lahir' => 'Surabaya',
                'ttl' => '1992-01-01',
                'foto_pengajar' => 'Siswa/foto.jpg',
                'jabatan' => 'Kepala Sekolah',
                'agama' => 'Protestan',
                'suku' => 'Batak',
                'rt_rw' => '010/000',
                'desa_kelurahan' => 'Teluk Lingga',
                'kecamatan' => 'Sangatta Utara',
                'kode_pos' => 75622,
            ],
            [
                'id' => 7,
                'nip' => 132264,
                'nama_guru' => 'Bu Jooo',
                'no_telp' => '324232324',
                'alamat_guru' => 'Jl. Selamat 1, No.27, Sangatta Utara, Kutai Timur, Kalimantan Timur',
                'tempat_lahir' => 'Bandung',
                'ttl' => '1992-01-01',
                'foto_pengajar' => 'Siswa/foto.jpg',
                'jabatan' => 'Kepala Sekolah',
                'agama' => 'Protestan',
                'suku' => 'Toraja',
                'rt_rw' => '011/000',
                'desa_kelurahan' => 'Teluk Lingga',
                'kecamatan' => 'Sangatta Utara',
                'kode_pos' => 75622,
            ],
            [
                'id' => 8,
                'nip' => 132264,
                'nama_guru' => 'Bu Rawrr',
                'no_telp' => '324232324',
                'alamat_guru' => 'Jl. Selamat 1, No.27, Sangatta Utara, Kutai Timur, Kalimantan Timur',
                'tempat_lahir' => 'Bandung',
                'ttl' => '1992-01-01',
                'foto_pengajar' => 'Siswa/foto.jpg',
                'jabatan' => 'Kepala Sekolah',
                'agama' => 'Protestan',
                'suku' => 'Manado',
                'rt_rw' => '090/000',
                'desa_kelurahan' => 'Teluk Lingga',
                'kecamatan' => 'Sangatta Utara',
                'kode_pos' => 75622,
            ],
            [
                'id' => 9,
                'nip' => 132264,
                'nama_guru' => 'Bu reer',
                'no_telp' => '324232324',
                'alamat_guru' => 'Jl. Selamat 2, No.27, Sangatta Utara, Kutai Timur, Kalimantan Timur',
                'tempat_lahir' => 'Bandung',
                'ttl' => '1992-01-01',
                'foto_pengajar' => 'Siswa/foto.jpg',
                'jabatan' => 'Kepala Sekolah',
                'agama' => 'Protestan',
                'suku' => 'Batak',
                'rt_rw' => '091/000',
                'desa_kelurahan' => 'Teluk Lingga',
                'kecamatan' => 'Sangatta Utara',
                'kode_pos' => 75622,

            ],
            [
                'id' => 10,
                'nip' => 132264,
                'nama_guru' => 'Bu Siskass',
                'no_telp' => '324232324',
                'alamat_guru' => 'Jl. Selamat 3, No.27, Sangatta Utara, Kutai Timur, Kalimantan Timur',
                'tempat_lahir' => 'Bandung',
                'ttl' => '1992-01-01',
                'foto_pengajar' => 'Siswa/foto.jpg',
                'jabatan' => 'Kepala Sekolah',
                'agama' => 'Protestan',
                'suku' => 'Jawa',
                'rt_rw' => '099/000',
                'desa_kelurahan' => 'Teluk Lingga',
                'kecamatan' => 'Sangatta Utara',
                'kode_pos' => 75622,
            ],
            [
                'id' => 11,
                'nip' => 132264,
                'nama_guru' => 'Bu asdad',
                'no_telp' => '324232324',
                'alamat_guru' => 'Jl. Selamat 10, No.27, Sangatta Utara, Kutai Timur, Kalimantan Timur',
                'tempat_lahir' => 'Bandung',
                'ttl' => '1992-01-01',
                'foto_pengajar' => 'Siswa/foto.jpg',
                'jabatan' => 'Kepala Sekolah',
                'agama' => 'Protestan',
                'suku' => 'Toraja',
                'rt_rw' => '097/000',
                'desa_kelurahan' => 'Teluk Lingga',
                'kecamatan' => 'Sangatta Utara',
                'kode_pos' => 75622,
            ],
        ]);
    }
}
